name: CI

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"
      - ".github/**"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  check:
    name: Check (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --workspace

  test:
    name: Test (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly

      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --workspace

  lint:
    name: Lint (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace -- -D warnings
